const users = [
  {
    id: 1,
    username: "john_doe",
    email: "john@example.com",
    firstName: "John",
    lastName: "Doe",
    age: 30,
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zipCode: "12345",
    },
    isActive: true,
  },
  {
    id: 2,
    username: "jane_smith",
    email: "jane@example.com",
    firstName: "Jane",
    lastName: "Smith",
    age: 25,
    address: {
      street: "456 Elm St",
      city: "Sometown",
      state: "NY",
      zipCode: "67890",
    },
    isActive: true,
  },
  {
    id: 3,
    username: "mike_jones",
    email: "mike@example.com",
    firstName: "Mike",
    lastName: "Jones",
    age: 28,
    address: {
      street: "789 Oak St",
      city: "Othertown",
      state: "TX",
      zipCode: "54321",
    },
    isActive: false,
  },
  {
    id: 4,
    username: "sara_adams",
    email: "sara@example.com",
    firstName: "Sara",
    lastName: "Adams",
    age: 35,
    address: {
      street: "101 Pine St",
      city: "Anycity",
      state: "FL",
      zipCode: "98765",
    },
    isActive: true,
  },
  {
    id: 5,
    username: "alex_wilson",
    email: "alex@example.com",
    firstName: "Alex",
    lastName: "Wilson",
    age: 22,
    address: {
      street: "210 Maple St",
      city: "Sometown",
      state: "WA",
      zipCode: "24680",
    },
    isActive: false,
  },
];
module.exports = users;
